### ISSUE TITLE
[Feature Request] Merge navigation into one button

### ISSUE THREAD

**Issue by Senexis** [outl1ne/nova-page-manager#100]
Hey there, OptimistDigital!

I thought I'd write in to request a feature from you guys! Currently, if you have regions or pages disabled, the navigation layout still uses a `UL` element to show the resources in the tool. It'd be a great addition for clarity sake to move the regions or pages link to the button itself.

Here's what I mean:
![image](https://user-images.githubusercontent.com/6360733/147464810-ee1d3df4-9ae7-4618-857f-f42198d503e8.png)

Which would turn into:
![image](https://user-images.githubusercontent.com/6360733/147464897-15db8709-93bd-47a7-9fb7-5869e7087c66.png)

What would be even greater is an option to just override the navigation view itself. I've been looking around a little but I was unable to come up with a functioning result. If there is a way to do this currently, it would be greatly appreciated if you could point me to said solution!

As an alternative, it would also be great if the resources could be moved to the Nova default "Resources" section, disabling the navigation view entirely. While this is not preferred for my use case, I feel like it could be another great addition. Thank you!

Have a good one!

**Comment by adin00** [comment]
@Senexis it is possible to override default navigation (this is true for any nova package): copy `vendor/optimistdigital/nova-page-manager/resources/views/navigation.blade.php` to `resources/views/vendor/nova-page-manager/navigation.blade.php`  then edit it as you like.

Below is the code to make the link look like in your screenshot:
```blade
<router-link dusk="nova-page-manager" tag="h3"
             :to="{ name: 'index', params: { resourceName: 'pages' } }"
             class="cursor-pointer flex items-center font-normal dim text-white mb-6 text-base no-underline">
    <svg viewBox="0 0 24 24" class="sidebar-icon">
        <path fill="var(--sidebar-icon)" fill="#000000" d="M16,15H9V13H16V15M19,11H9V9H19V11M19,7H9V5H19V7M3,5V21H19V23H3A2,2 0 0,1 1,21V5H3M21,1A2,2 0 0,1 23,3V17C23,18.11 22.11,19 21,19H7A2,2 0 0,1 5,17V3C5,1.89 5.89,1 7,1H21M7,3V17H21V3H7Z" />
    </svg>
    <span class="sidebar-label">
        @lang("novaPageManager.navigationPagesTitle")
    </span>
</router-link>
```
