### ISSUE TITLE
Localization and Drafts don't play well together

### ISSUE THREAD

**Issue by adin00** [outl1ne/nova-page-manager#101]
Drafts on secondary locales are lost on every edit, unless the user knows exactly how to handle the problem.

Here's the scenario: 
- have 2 locales, let's say `en` and `es`
- create a new page in `en`
- from the index page, create a child page in `es` using the `+ es` button on listing, and publish it
- return to index, press `✏️  es` then save the updated page as draft (with `create draft` button)

At this point the draft page is not accessible in normal navigation -- repeating previous step will open original page, and an attempt to create another draft will result in a DB error. 
The only workaround to find the draft is to filter index by `es` locale then edit/publish/discard

**Comment by Tarpsvo** [comment]
The drafts and localization logic of Page Manager V4 is scuffed. I just released a new version (5) with Nova 4 support that is a complete rework of the page manager that is more stable, albeit missing some features right now.

I'm not going to fix these issues for the old page manager and will focus on maintaining the new rework. Sorry about that!
