### ISSUE TITLE
Duplicate pages, especially for translations

### ISSUE THREAD

**Issue by JeremDigi** [outl1ne/nova-page-manager#102]
Hello,

Thank you very much for this package (and all the others) that help me build a headless CMS.

For the construction of my pages, I often use "flexible content".

When I have a page in English and I want to translate it into another language, my structure is not taken over. Same for some non-translatable fields (ex: images).

Is there a way with your package to "duplicate" the current content when creating a new translation? In such a way that my structure would remain the same and the images would not have to be added again.

Thanks for your help

**Comment by Tarpsvo** [comment]
Hey! Currently, it's not possible. However, I am working on a new major release of the page manager which would add that functionality.

**Comment by JeremDigi** [comment]
Great, thank you @Tarpsvo. I am happy to see this new version. 
Do you have an idea (without pressure) of when it will be available? Thank you
