### ISSUE TITLE
Compatible with whitecube/nova-flexible-content

### ISSUE THREAD

**Issue by bigperson** [outl1ne/nova-page-manager#118]
Laravel 9
Nova 4

I have error 
exception: "Exception"
file: "/var/www/alarm.ru/vendor/whitecube/nova-flexible-content/src/Flexible.php"
line: 394
message: "Unable to parse incoming Flexible content, data should be an array."
trace: [{file: ".../vendor/whitecube/nova-flexible-content/src/Flexible.php", line: 332,…},…]
0: {file: ".../vendor/whitecube/nova-flexible-content/src/Flexible.php", line: 332,…}
1: {file: ".../vendor/whitecube/nova-flexible-content/src/Flexible.php", line: 310,…}
2: {file: ".../vendor/laravel/nova/src/Fields/Field.php", line: 428,…}
3: {file: ".../vendor/laravel/nova/src/Fields/Field.php", line: 402, function: "fillInto",…}
4: {,…}
5: {function: "Illuminate\Support\{closure}", class: "Illuminate\Support\HigherOrderCollectionProxy",…}
6: {file: ".../vendor/laravel/framework/src/Illuminate/Collections/Arr.php", line: 560,…}
7: {file: ".../vendor/laravel/framework/src/Illuminate/Collections/Collection.php",…}
8: {,…}
9: {file: ".../vendor/outl1ne/nova-page-manager/src/Nova/Fields/PageManagerField.php",…}
class: "Illuminate\\Support\\HigherOrderCollectionProxy"
file: ".../vendor/outl1ne/nova-page-manager/src/Nova/Fields/PageManagerField.php"
function: "__call"
line: 81
type: "->"

**Comment by dmitrijsmihailovs** [comment]
Same error here. Have latest versions for Laravel, Nova, Page Manager, Flexible content

**Comment by Tarpsvo** [comment]
Hi! Page manager 5.2.0 now has support for the Flexible Content package. Worked on my machine, even nested Flexibles seemed to work.

I had to add a lot of fairly complicated logic to get it to work, so please test it out and let me know how it works on your side. If there's any corner-cases or other issues, do let me know by opening a new issue. Thank you!

**Comment by matthewjumpsoffbuildings** [comment]
@Tarpsvo I am still getting the same issue/error message, eg
```
Unable to parse incoming Flexible content, data should be an array.
```

**Comment by matthewjumpsoffbuildings** [comment]
I have noticed that rolling back to Nova Page Manager version 5.7.3 allows Flexible Content fields to work, eg you can submit the form and it updates correctly, though it does throw the following JS error in the console on form submit:
```
nova-page-manager:2 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Le (nova-page-manager:2:63142)
    at Proxy.getDataFromFill (nova-page-manager:2:74029)
    at Proxy.addFieldValuesToFormData (nova-page-manager:2:73506)
    at Proxy.fill (nova-page-manager:2:73363)
    at Update.vue:307:19
    at e.exports (_arrayEach.js:15:9)
    at e.exports (forEach.js:37:48)
    at Update.vue:306:11
    at e.exports (_arrayEach.js:15:9)
    at e.exports (forEach.js:37:48)
```
However Nova Page Manager 5.8.2 does not allow submission to work, on the PHP side, eg it throws a server error
```
Unable to parse incoming Flexible content, data should be an array.
```
