### ISSUE TITLE
Issue in Region.php (Panel Feature) with trailing comma at #41

### ISSUE THREAD

**Issue by ds-pda5** [outl1ne/nova-page-manager#12]
I think one of the latest updates in the Region.php is breaking in pre-PHP 7.3

On line 41 of Region.php, there is a trailing "," comma that causes the error. 

Similar code is in Page.php without the breaking "'" comma. 

Just noticed when doing a test deploy. 

![image](https://user-images.githubusercontent.com/51957326/59682288-eb023d00-91a3-11e9-8218-d2b6dda2ab54.png)

**Comment by Tarpsvo** [comment]
Hey! Thanks for reporting this, fixed in 1.8.2. 👍 A stupid typo by me.
