### ISSUE TITLE
Error when 'page_seo_fields' => true in config

### ISSUE THREAD

**Issue by johnpuddephatt** [outl1ne/nova-page-manager#129]
When page_seo_fields is set to true, I get the following error when trying to use `NPMHelpers::getPageByTemplate($templateName)`:

```
array_map(): Argument #2 ($array) must be of type array, null given
```

The problem goes away when I set page_seo_fields to an empty array.

**Comment by KasparRosin** [comment]
Hey @johnpuddephatt!

Thanks for reporting.
Fixed this in version 5.5.3.
