### ISSUE TITLE
Panels dont have any impact on `data` JSON now?

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [outl1ne/nova-page-manager#134]
I'm using `Laravel\Nova\Panel` to structure my content, and the JSON thats being saved is totally different to what it used to be when this was in Nova 3 - for starters now the data field is wrapped in a local object eg `{ "en": {... }}` which is fine enough I guess

But on top of that, while it used to be the case Panels would create nice nested data, eg
```json
{
	"banner": {
		"mobile": "JLRZOs1S8GIxCeU6E0SSpPxvo2kUcKpzi7UeRCIO.png",
		"tablet": "Rt6E9uFsdKExKdZG124Mzdotm56vM2hX5X1bA64H.png",
		"desktop": "7I7olt5QzvgXPHsKkJw6NOtVLxPQlGb3Fiivv92P.png"
	},
	"masthead": {
		"js": "main.js",
		"css": "main.css",
		"site": "site-name"
	},
}
```
Now its just creating a flat mess with no structure based on the Panels... eg
```json
{
	"tablet": "Rt6E9uFsdKExKdZG124Mzdotm56vM2hX5X1bA64H.png",
	"desktop": "7I7olt5QzvgXPHsKkJw6NOtVLxPQlGb3Fiivv92P.png"
	"js": "main.js",
	"css": "main.css",
	"site": "site-name"
}
```
Am I doing something wrong or does this stink now?

**Comment by KasparRosin** [comment]
The panels without any configuration don't have an impact indeed. They work as they would in regular nova resource.
We did add a helper function, that is yet to be documented, called `fieldPrefix` that you can use to give a prefix to the fields.

```php
Panel::make('Banner', [
    Text::make('Mobile'),
    Text::make('Tablet'),
    Text::make('Desktop')
])->fieldPrefix('banner'),
```

**Comment by matthewjumpsoffbuildings** [comment]
@KasparRosin confirmed this works, but its so strange that its necessary? Surely the behaviour achieved by adding the `fieldPrefix('name')`, identical to how the old Nova 3.0 version of this package worked, is ideal and should be default? Is there a good reason for having `Panel` store its data flat by default, breaking migrations from the old package even more etc?

**Comment by Tarpsvo** [comment]
There were issues with people writing the panel names in localized languages. Imagine accessing a property that is in greek for example. So we had to give panels an explicit way of defining a prefix. So yeah, all is fine and dandy when you're writing the CMS in English, but hell breaks loose once you start writing things that are not in the latin alphabet. :(

**Comment by matthewjumpsoffbuildings** [comment]
Then why not do this
Edit: see pull request below
Here: https://github.com/outl1ne/nova-page-manager/blob/main/src/Nova/Fields/PageManagerField.php#L116

Best of both worlds. Cleaner `Panel` syntax for most use cases, nicer default behaviour, more compatible with old version out of the box, then _if_ you need to override the prefix, you can

**Comment by matthewjumpsoffbuildings** [comment]
FYI, in the case someone has, say, a Greek panel name, `Str::slug('Ελληνικά')` returns `ellinika` - not the end of the world, and with my suggested change, the user can still decide to override it by doing `Panel->fieldPrefix('whatever')` if they want
