### ISSUE TITLE
Depends on Laravel 9, but that dependency is not specified in composer.json

### ISSUE THREAD

**Issue by wdelfuego** [outl1ne/nova-page-manager#138]
The current `composer.json` allows installation in a Laravel 8 application, but that causes the `Arr::map does not exist` error described in [this issue](https://github.com/outl1ne/nova-page-manager/issues/131).

I suppose either the `composer.json` should be updated to reflect this dependency on Laravel 9 or the project should be made backwards compatible with Laravel 8.

**Comment by Tarpsvo** [comment]
Heya. I removed the Arr::map calls in version 5.8.4. I hope this fixed the backwards compatibility. I had no idea it was added with Laravel 9. Good luck!
