### ISSUE TITLE
Error: Undefined array key "__"

### ISSUE THREAD

**Issue by wdelfuego** [outl1ne/nova-page-manager#139]
Hi,

thanks for a great package!

I added the package to my project, followed all setup instructions, but get the following error when I open the Detail and Edit views for a page I created:

`Undefined array key "__" {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key \"__\" at /app/vendor/outl1ne/nova-page-manager/src/Http/Controllers/PageManagerController.php:118)`

In that file at line 118, I see that `$seoPanelsData['__']` is supposed to exist, but doesn't.

Am I doing something wrong? Should I add SEO fields to the page template manually in order to fix this error?

Running under Laravel Nova 4.18.1 / Laravel 9 / PHP 8.1.5

Thanks for any help!

**Comment by Tarpsvo** [comment]
Hey @wdelfuego! Sorry about that - there was indeed an issue with the template fields formatter. Please try again using version 5.8.1. Good luck!
