### ISSUE TITLE
"Undefined array key \"__\"" On Nova Edit Page

### ISSUE THREAD

**Issue by jeh5256** [outl1ne/nova-page-manager#158]
If you have "page_seo_fields" set as false in the config file then visit the Page resource edit page it will throw a 500 error and return a message of `"Undefined array key \"__\"`

` "message": "Undefined array key \"__\"", 
    "exception": "ErrorException", 
/
    "file": "/sites/mcd-kmp/vendor/outl1ne/nova-page-manager/src/Http/Controllers/PageManagerController.php", 
    "line": 103,`

Running php 8.1.5, Laravel 9, Nova 4.23

**Comment by Tarpsvo** [comment]
I added a theoretical fix for this in version 5.9.0. Thanks for the report!
