### ISSUE TITLE
 overwriting page_seo_fields with a callable that returns an array of fields gives error on config caching

### ISSUE THREAD

**Issue by Napia** [outl1ne/nova-page-manager#159]
I am trying to replace the image seo field with a text field. So I set "page_seo_fields" in the nova-page-manager to a callable that returns an array of fields. At first sight everything works fine, but on calling artisan config:cache as I do in my deploy script it gives an error:

`  LogicException:  Your configuration files are not serializable.`

![image](https://github.com/outl1ne/nova-page-manager/assets/10514127/7a1c8874-4d43-414e-8684-f9d1f9c98fb6)

Is there any other possibility to replace the seo fields? 
Thank you!

**Comment by Tarpsvo** [comment]
Heya! There was an option before to create a dedicated class or a global function and reference it in config as a callable.

However, I added a new option to the Tool instance now to modify the SEO fields.

You can do it in your NovaServiceProvider tools() like so:
```
public function tools()
{
    return [
        PageManager::make()
            ->withSeoFields(function() {
                return [...];
            }),
    ];
}
```
