### ISSUE TITLE
PrefixSlugField has no value

### ISSUE THREAD

**Issue by ZakariaTlilani** [outl1ne/nova-page-manager#174]
Nova version : 4.32.14 (latest up today).

PrefixSlugField field works but when submitting the form it sends value of " " (single space).

**Comment by ZakariaTlilani** [comment]
@allantatter @trippo  @Landish  @RibesAlexandre  what do you think can be done in this regard ?

**Comment by KasparRosin** [comment]
Could you share you setup, the way you use it & did this happen with latest nova release?
