### ISSUE TITLE
Tips : Nova >= 2.0.7

### ISSUE THREAD

**Issue by tonyyb** [outl1ne/nova-page-manager#18]
I've found solution for Nova > 2.0.7

There is a bug introduced by Nova with panels. Will be fixed in next release (I've seen the commit).

Solution : 

You have to update `nova/src/Http/Controllers/UpdateFieldController.php`

With : 

```php
public function index(NovaRequest $request)
{
    $resource = $request->newResourceWith($request->findModelOrFail());
    $resource->authorizeToUpdate($request);

    return response()->json([
            'fields' => $resource->updateFieldsWithinPanels($request),
            'panels' => $resource->availablePanelsForUpdate($request),
        ]);
}
```

Best regards.

**Comment by Tarpsvo** [comment]
Yes, I know, I made the commit. Waiting for next Nova to be released (for a month now).
