### ISSUE TITLE
Issue with HEREDOC syntax on Page.php (PHP 7.2.24)

### ISSUE THREAD

**Issue by zedee** [outl1ne/nova-page-manager#25]
I installed this package following the instructions, but when I go to Nova admin panel, I get the following error:

```
Facade\Ignition\Exceptions\ViewException
syntax error, unexpected ']', expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) (View: /var/www/nova/resources/views/layout.blade.php)
```

Which can be tracked to this file:

```
vendor/optimistdigital/nova-page-manager/src/Nova/Page.php
```

On this file, I found the offending lines (60-69) using HEREDOC syntax:

```
if (empty($pageBaseUrl)) return <<<HTML
                    <span class="bg-40 text-sm py-1 px-2 rounded-lg whitespace-no-wrap">$pagePath</span>
                HTML;

                return <<<HTML
                    <div class="whitespace-no-wrap">
                        <span class="bg-40 text-sm py-1 px-2 rounded-lg">$pagePath</span>
                        <a target="_blank" href="$pageUrl" class="text-sm py-1 px-2 text-primary no-underline dim font-bold">$buttonText</a>
                    </div>
                HTML;
```

Found that when using HEREDOC syntax, in this case, the ending `HTML` on both statements *must* be on first character of the line, at least up to PHP 7.2 (https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) 
Changing those lines to this:

```
if (empty($pageBaseUrl)) return <<<HTML
                    <span class="bg-40 text-sm py-1 px-2 rounded-lg whitespace-no-wrap">$pagePath</span>
HTML;

                return <<<HTML
                    <div class="whitespace-no-wrap">
                        <span class="bg-40 text-sm py-1 px-2 rounded-lg">$pagePath</span>
                        <a target="_blank" href="$pageUrl" class="text-sm py-1 px-2 text-primary no-underline dim font-bold">$buttonText</a>
                    </div>
HTML;
```

Seems to fix the problem.
I guess that in PHP 7.3, this issue probably doesn't happen, but this package should be compatible with current Laravel minimum PHP version (PHP >= 7.2.0)

Could anyone please confirm? I'd do the PR by myself if its confirmed.

**Comment by Tarpsvo** [comment]
Hey! Sorry for the late reply. I removed the usage of HEREDOC and released a new version without it, 2.0.3. Give it a try, I hope it fixes the crash on PHP 7.2. Good luck!
