### ISSUE TITLE
Drafts

### ISSUE THREAD

**Issue by miccidk** [outl1ne/nova-page-manager#49]
When you unpublish a page it does not set the preview_token again.
Maybe this should be added?

**Comment by liorocks** [comment]
@miccidk https://github.com/optimistdigital/nova-drafts/pull/7

**Comment by Tarpsvo** [comment]
Hi! Thanks for reporting this and thanks a ton to @Landish for the PR! I released version 1.1.1 of nova-drafts which includes the fix. All the best!
