### ISSUE TITLE
How do you add a region to a page?

### ISSUE THREAD

**Issue by davidmuggleton** [outl1ne/nova-page-manager#6]
How do you add a region to a page? I can't see anything in the documentation or code allowing you to do so?

**Comment by Tarpsvo** [comment]
Do you mean a region? Regions weren't really meant to be embedded inside a page. The front-end code should know/decide where the region resides.

**Comment by davidmuggleton** [comment]
Hi @Tarpsvo thanks for the quick response! Just curious in one of the screenshots you posted:

![image](https://user-images.githubusercontent.com/15907082/57085751-c2f27380-6cf4-11e9-8a64-713ae0c627a7.png)

There's a "Banner" section with an icon bar allowing you to order/delete the section as well as a "Add Layout" button. Is that something powered by this package or is it an external package you're using?

**Comment by Tarpsvo** [comment]
That's the [Nova Flexible Content](https://github.com/whitecube/nova-flexible-content) package that essentially allows you have repeater fields.

**Comment by davidmuggleton** [comment]
Amazing, thank you!
