### ISSUE TITLE
Error creating a region in the postgres database

### ISSUE THREAD

**Issue by shahruslan** [outl1ne/nova-page-manager#64]
While creating a region, I get an error:
```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: "{{resourceId}}" (SQL: select count(*) as aggregate from "nova_page_manager_regions" where "template" = footer-region and "id" <> {{resourceId}} and "locale" = en)
```
In Mysql(and mariadb), this sql is executed normally, but in the postgres it does not allow it to be executed due to the fact that "{{resourceId}}" string does not correspond to the bigInt type.

**Comment by Tarpsvo** [comment]
That's weird. Nova is supposed to replace {{resourceId}} with the actual resourceId. What's your Nova version?

**Comment by shahruslan** [comment]
3.13.0

**Comment by Tarpsvo** [comment]
Ah yes, I think I got it. Please try out version 3.2.3 and let me know if it works better now. :) Thanks!

**Comment by shahruslan** [comment]
Great, everything works! thanks
