### ISSUE TITLE
Database error after moving from mysql to psql

### ISSUE THREAD

**Issue by Iznaur** [outl1ne/nova-page-manager#73]
Hello,  after changing database saving pages doesn't work for me, i get that error:
`"SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type boolean: "{{published}}" (SQL: select count(*) as aggregate from "nova_page_manager_pages" where "slug" = / and "id" <> 1 and "published" = {{published}} and "locale" = en and "parent_id" is null)"`
How can I fix it?

**Comment by KasparRosin** [comment]
Released 3.5.0 that should hopefully fix this issue. Let us know if this issue persists after updating version.
