### ISSUE TITLE
BelongsToMany Relationship Not Working on Page Template

### ISSUE THREAD

**Issue by lhilton** [outl1ne/nova-page-manager#79]
Like the title says, when I define the following Page template, the relationship is all kinds of broken:

```php
<?php

namespace App\Nova\Templates;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsToMany;
use OptimistDigital\NovaPageManager\Template;

class DocumentsPageTemplate extends Template
{
    public static $type = 'page';
    public static $name = 'carousel';
    public static $seo = false;
    public static $view = null;

    public function fields(Request $request): array
    {
        return [
            BelongsToMany::make('Documents')
        ];
    }
}
```

It looks like there are problem from two areas: first, the field isn't listed on some of the `nova-api` calls. Deeper in, the field attribute ends up prefixed with `data->`, breaking more Nova stuff. I did a LOT of hackery to get this working on my setup, but I am curious if maybe I'm just doing something wrong or if this is a known-issue?

**Comment by Tarpsvo** [comment]
Hi! When I designed this package, I didn't really have BelongsToMany support in mind, so yeah, this is normal that it does not work out of the box right now.

One easier way to make it work would be to override the Page model and resource and then add the BelongsToMany field into the default panel.
