### ISSUE TITLE
Configuration caching error

### ISSUE THREAD

**Issue by shahruslan** [outl1ne/nova-page-manager#81]
If in the `nova-page-manager.php` file, in the seo_fields key, specify an array of fields of the `Text` type:

```
    'seo_fields' => [
        Text::make('SEO Title', 'title_seo'),
        Textarea::make('SEO Description', 'description_seo'),
        Text::make('SEO Keywords', 'keywords_seo'),
    ],
```

when caching the configuration(`php artisan optimize`), we get an error:
`Method Laravel\\Nova\\Fields\\Text :: __ set_state does not exist.`
The Callable array is working fine.

**Comment by Tarpsvo** [comment]
Hmm, I think you might need to use a callable for that. Define a global function (or a static class function) and use that as the config value instead. Ie:

```
function get_pagemanager_seo_fields() {
  return [
    // ...
  ];
}

// ...

'seo_fields' => 'get_pagemanager_seo_fields',
```

**Comment by shahruslan** [comment]
Yes, that's exactly what I did.
I think this should be written in the documentation(readme). So that other people don't have problems.
