### ISSUE TITLE
First instead of firstOrFail

### ISSUE THREAD

**Issue by shahruslan** [outl1ne/nova-page-manager#83]
![img](https://user-images.githubusercontent.com/45426321/119344453-5c0bd280-bca0-11eb-93ae-f4c1564568fe.jpg)

In all cases, you return null, and here an exception is thrown. Next comes the check of the $page variable for empty. But it will fail, because if $page is not found, then an exception is thrown.

https://github.com/optimistdigital/nova-page-manager/blob/2b55e4a4a886f052016fec17e144c2c3f83fbd26/src/helpers.php#L221

**Comment by Tarpsvo** [comment]
Heya! I merged the related PR and released the change in version 4.0.0. Thanks!
