### ISSUE TITLE
Can't access page on frontend

### ISSUE THREAD

**Issue by NowakAdmin** [outl1ne/nova-page-manager#92]
Hello,

I'm trying to test Your package and i can't access to www.some_domain.com/page-path it gives me an 404 error.

Do i need to add anything to laravel routes ?
my page_url: (i needed to remove extra "/" becouse somehow it shows doubled "//" when i click "View" next to slug.
nova-page-manager.php

``` 
use OptimistDigital\NovaPageManager\Models\Page;
//
'page_url' => function (Page $page) {
           return env('FRONTEND_URL') . $page->path;
         }, 
```

I don't see also in readme adding a extra line to .env or it should be replaced to default env('APP_URL')
`FRONTEND_URL=www.some_domain.com`

Launched on: 
Laravel Framework 8.52.0
Nova 3.27

**Comment by Tarpsvo** [comment]
Hi! This package does not automatically create pages for you. It's meant to simplify filling page data in the CMS, you have to handle everything about creating and displaying the pages yourself.
