### ISSUE TITLE
in production region goes to 404 unless i override Region and put $displayInNavigation = true, but in local it works without it

### ISSUE THREAD

**Issue by SerjoA** [outl1ne/nova-page-manager#93]

**Comment by Tarpsvo** [comment]
Hi! Does this only happen for regions and not pages? What URL does it redirect you to? I can't reproduce this and need more info sadly.

**Comment by SerjoA** [comment]
redirect to 404
nova version: 3.27.0
as soon as i move .env file to production it happens, in local its not happening
also, if i overwrite those models its not happening
