### ISSUE TITLE
[bug] N+1 Query Issue(s) in Nova Index view

### ISSUE THREAD

**Issue by rk** [outl1ne/nova-page-manager#97]
Hi,

With 97 records, and some nesting, displaying pages results in an N+1 query issue.

![page_manager_n1_issue](https://user-images.githubusercontent.com/58199/134965812-96cf385e-e877-47e5-9dd6-ef0f1f663967.png)

I have traced this back to the `Page::getPathAttribute()` implementation. It's not optimized for loading via Nova, and doesn't cache any of the intermediary models. We should be able to mostly solve this with an eager load on the Nova view, but adding a `$with = ['parent']` property to the Nova definition didn't do anything for me. So at this point, I'm concerned that it's in the logic itself.

**Comment by Tarpsvo** [comment]
Yup - it's definitely in the logic itself. The path generation isn't very smart in that regard. This whole package needs a proper rewrite one day, so I guess it'll be fixed then at least.

**Comment by Tarpsvo** [comment]
Hi! @allantatter made some improvements to the index view, so there's fewer queries now. It should now be a lot better.
